
# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/products_db
#     username: vinod_mudavath
#     password: Mangi@143
#   jpa:
#     database-platform: org.hibernate.dialect.MySQL8Dialect
#     hibernate:  
#       ddl-auto: validate    # use Flyway for schema management
#     show-sql: true
    
#     properties:
#       hibernate:
#         format_sql: true

#   flyway:
#     enabled: true
#     locations: classpath:db/migration

# server:
#   port: 8080

# jwt:
#   secret: change_this_to_a_long_random_secret_string_at_least_32_chars
#   expiration: 86400000


spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/products_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:  
      ddl-auto: update    # use flyway for schema; use 'update' only for dev
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:change_this_to_a_long_random_secret_string_at_least_32_chars}
  expiration: ${JWT_EXPIRATION:86400000}

