
spring:
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: gYBzdvlsuOgxxWCQqpyzmUOXUofwMRdK
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:  
      ddl-auto: update    # use flyway for schema; use 'update' only for dev
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false   # disable to avoid Unsupported Database error and unblock startup

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:change_this_to_a_long_random_secret_string_at_least_32_chars}
  expiration: ${JWT_EXPIRATION:86400000}
